name: Docker
on:
  push:
    branches:
      - master
      - stable
    tags:
      - v[0-9]*
  pull_request:
    branches:
      - master
      - stable
  schedule:
    - cron:  '0 5 * * FRI'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: votca
      - name: Build Docker images for Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/votca
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: votca/.github/workflows/Dockerfile
          tag_with_ref: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Github Container Registry
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/votca
          registry: ghcr.io
          # username do not matter, but needs to be a secret, so it gets nulled out on PR from forks
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.VOTCA_BOT_TOKEN }}
          dockerfile: votca/.github/workflows/Dockerfile
          tag_with_ref: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Gitlab
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/votca
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          dockerfile: votca/.github/workflows/Dockerfile
          tag_with_ref: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
